personUrl = "data/person.json";
excelFile = "file/人员信息.xlsx";
trayFile = "file/托盘信息.xlsx";
uploadFile = ""; // 文件上传接口
equitypeUrl = "data/equitype.json"; // 设备类型接口
equipmentUrl = "data/equipment.json"; // 设备接口
stationUrl = "data/station.json"; // 工位数据接口
padUrl = "data/pad.json"; // PAD 终端接口
materielUrl = "data/materiel.json"; // 物料接口
throughput = "data/throughput.json"; // 生产能力管理
setPersons = "data/dialog/data/"; // 生产能力管理
procedureUrl = "data/procedure.json"; // 生产能力管理
proceStationUrl = "data/proceStation.json"; // 生产能力管理
routeUrl = "data/route.json"; // 生产能力管理
trayeUrl = "data/tray.json"; // 生产能力管理
lineUrl = "data/line.json"; // 生产能力管理
lineJsonUrl = "data/dialog/data/line.json"; // 生产能力管理
